[platformio]
build_dir = C:\Users\jaran\.pio_build\Robotic_Arm

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = COM3
lib_deps =
    arduino-libraries/Servo
